<a href="https://colab.research.google.com/github/Patstach/DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

Biblioteka

In [357]:
import numpy as np

* Sklara czyli pojedyncza cyfra jest 0-wymiarowym tensorem (0D)
* Wektor to tensor 1-wymiarowy (1D)
* Macierz to tensor 2-wymiarowy (2D)
* Wystepuje też macierz 3-wymiarowa, jest to tensor (3D)

#**WEKTOR**

In [358]:
df = np.array([[1,2,3],[4,5,6]]) 
df

array([[1, 2, 3],
       [4, 5, 6]])

In [359]:
np.shape(df)

(2, 3)

1) Tworzenie wektorów, czyli tensora 1-wymiarowego (1D)

  * poprzez uzycie listy:

In [360]:
wektor = np.array([1, 2, 3, 4, 5, 6])
wektor

array([1, 2, 3, 4, 5, 6])

      lub:

In [361]:
mylist = [1, 2, 3, 4, 5]                                                        # Tworzymy wczesniej liste
mylist

[1, 2, 3, 4, 5]

In [362]:
wektor2 = np.array(mylist)                                                      # Tworzymy wektor z wczesniejszej listy
wektor2

array([1, 2, 3, 4, 5])

2) Tworzenie wektora w sytuacji w której wiemy jakie maja być wartości - ciąg liczbowy

In [363]:
wektor3 = np.arange(2,8,2)
wektor3                                                                         # podajemy wartość początkową (np.2), końcową (np.8), z przeskokiem co 2.

array([2, 4, 6])

3) Tworzenie wektora, jeśli chcemy stworzyć wartości w RÓWNYCH odstepach

In [364]:
wektor4 = np.linspace(0, 10, 3)                                                 # stworzy wektor z 3 elementami (ostatni argument), pierwszy to poczatek przedzialu, 
wektor4                                                                         #  drugi to koniec przedziału

array([ 0.,  5., 10.])

4) Zerowy wektor

In [365]:
wektor5 = np.zeros(4)                                                           # wektor zerowy z 4 elementami
wektor5

array([0., 0., 0., 0.])

5) Jedynkowy wektor

In [366]:
wektor6 = np.ones(5)                                                            # wektor jedynkowy z 5 elementami
wektor6

array([1., 1., 1., 1., 1.])

6) Wektor ze stałą wartością

In [367]:
wektor7 = np.full((5),7)                                                        # wektor z 5 elementami i stałą wrtością elementów (7)
wektor7

array([7, 7, 7, 7, 7])

7) Wektor pusty - Należy używać ostrożnie

In [368]:
wektor8 = np.empty((3))                                                         # Tworzy 'pusty' wektor który należy samemu uzupełnić?
wektor8

array([ 0.,  5., 10.])

8) Wektor z losowymi wartościami

In [369]:
wektor9 = np.random.random(5)                                                   # wektor z 5 losowymi elementami
wektor9

array([0.82104341, 0.50611097, 0.22513156, 0.84386678, 0.35621772])

#**MACIERZ**

Macierz jest 2-wymiarowym tensorem, wiekszosc procedur jest wykonywana analogiczne do wektora. Należy podawać jedynie argumenty dla '2-go wymiaru'
np.

In [370]:
macierz = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10]])
macierz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [371]:
macierz2 = np.array([np.random.randint(3, 10, size=3),
                     np.random.randint(3,10, size=3)])
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [372]:
macierz3 = np.array([np.arange(0, 10, 3),
                    np.arange(10, 20, 3)])
macierz3

array([[ 0,  3,  6,  9],
       [10, 13, 16, 19]])

In [373]:
macierz4 = np.array([np.linspace(0, 10, 3),
                    np.linspace(10, 20, 3)])
macierz4

array([[ 0.,  5., 10.],
       [10., 15., 20.]])

In [374]:
macierz5 = np.zeros((4,4))                                                      # macierz zerowa 4x4
macierz5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [375]:
macierz6 = np.ones((5,5))                                                       # macierz jedynkowa 4x4
macierz6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [376]:
macierz7 = np.full((5,4),7)                                                     # macierz 5x4 ze stałą wrtością elementów (7)
macierz7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [377]:
macierz9 = np.random.random((5,5))                                              # macierz 5x5 z losową wartościa elementów                  
macierz9

array([[0.57953902, 0.39548006, 0.84203907, 0.70618343, 0.27608973],
       [0.21293778, 0.29995869, 0.61747209, 0.72158846, 0.34174634],
       [0.31234377, 0.64084684, 0.13122441, 0.59781591, 0.65325762],
       [0.04790158, 0.09584931, 0.20034563, 0.3663862 , 0.26422151],
       [0.81840157, 0.67167492, 0.66409475, 0.3281231 , 0.8577234 ]])

In [378]:
macierz10 = np.identity(3)                                                      # macierz kwadratowa jednostkowa 3x3
macierz10

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [379]:
macierz11 = np.eye(3,4)                                                         # macierz 2D z przekątną z '1', reszta elementow '0', nie musi być kwadratowa
macierz11

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [380]:
macierz12 = np.eye(4, 5, k = 2)                                                 # można przesuwać przekątną z 1 za pomocą parametru k, jeżeli k>0 to przesuwamy po kolumnach
macierz12

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [381]:
macierz12 = np.eye(4, 5, k = -2)                                                 # można przesuwać przekątną z 1 za pomocą parametru k, jeżeli k<0 to przesuwamy po wierszach
macierz12

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

#**Atrybuty NUMPY**

1) Jesli chcemy dowiedzieć sie o skaldni danego atrybutu możemy to z robić za pomocą atrybutu. np

In [382]:
np.info(np.arange)                                                              # w tym przypadku wyrzuci nam instrukcję dotyczącą atrybutu 'arange'

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`. See the warnings section below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
    between t

2) Ilość wierszy i kolumn

In [383]:
macierz9.shape                                                           # na podstawie wczesniej stworzonej zmiennej 'macierz9' - 5 wierszy i 5 kolumn (macierz-> 2 wymiary)

(5, 5)

In [384]:
wektor7.shape                                                                   # na podstawie wczesniej stworzonej zmiennej 'wektor7' - 5 elementów (wektor-> 1 wymiar)

(5,)

3) Ilość elementów macierzy/wektora

In [385]:
macierz7.size                                                                   # na podstawie wczesniej stworzonej zmiennej 'macierz7'

20

In [386]:
wektor3.size                                                                    # na podstawie wczesniej stworzonej zmiennej 'wektor3'

3

4) Ilość wymiarów - sprawdzamy czy jest to wektor, macierz 2D, macierz 3D

In [387]:
macierz4.ndim                                                                   # na podstawie wczesniej stworzonej zmiennej 'macierz4' -> 2 wymiary bo macierz

2

In [388]:
wektor2.ndim                                                                    # na podstawie wczesniej stworzonej zmiennej 'wektor2' -> 1 wymiar bo wektor

1

5) Typ elementów macierzy/wektora (int64, float32, complex, bool, object, string, unicode)



In [389]:
macierz7.dtype

dtype('int64')

In [390]:
wektor3.dtype

dtype('int64')

6) Zmiana typu elementów

In [391]:
macierz7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [392]:
macierz7.dtype

dtype('int64')

In [393]:
macierz7.astype(str)                                                            # zamiana elementów na 'str'

array([['7', '7', '7', '7'],
       ['7', '7', '7', '7'],
       ['7', '7', '7', '7'],
       ['7', '7', '7', '7'],
       ['7', '7', '7', '7']], dtype='<U21')

7) Sprawdzenie czy aarray zawiera element NaN

In [394]:
macierz12 = np.array([[1, 2, 4, np.nan],
                     [3, np.nan, 6, 7]])
macierz12

array([[ 1.,  2.,  4., nan],
       [ 3., nan,  6.,  7.]])

In [395]:
np.isnan(macierz12)

array([[False, False, False,  True],
       [False,  True, False, False]])

8) Operacja logiczna 'and'

In [396]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [397]:
np.logical_and(x > 1, x < 4)

array([False, False,  True,  True, False])

9) Operacja logiczna 'lub'

In [398]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [399]:
np.logical_or(x > 1, x < 4)

array([ True,  True,  True,  True,  True])

10) Zaprzeczenie logiczne

In [400]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [401]:
np.logical_not(x < 3)                                                           # jeśli warunek jest True, to metoda zwraca nam False i odwrotnie

array([False, False, False,  True,  True])

11) Operacja logiczna 'wieksze'

In [402]:
macierz13 = np.random.random((3,3))            
macierz13

array([[0.98284497, 0.11144726, 0.60218667],
       [0.88458041, 0.41930201, 0.53887288],
       [0.27278745, 0.4692638 , 0.46308456]])

In [403]:
macierz14 = np.random.random((3,3))            
macierz14

array([[0.93830768, 0.44237549, 0.66145077],
       [0.40772167, 0.89078838, 0.82076795],
       [0.43863284, 0.62568708, 0.83384832]])

In [404]:
macierz13 > macierz14

array([[ True, False, False],
       [ True, False, False],
       [False, False, False]])

      lub

In [405]:
np.greater(macierz13, macierz14)

array([[ True, False, False],
       [ True, False, False],
       [False, False, False]])

12) Operacja logiczna 'wieksze i rowne'

In [406]:
macierz13 >= macierz14

array([[ True, False, False],
       [ True, False, False],
       [False, False, False]])

      lub

In [407]:
np.greater_equal(macierz13, macierz14)

array([[ True, False, False],
       [ True, False, False],
       [False, False, False]])

13) Operacja logiczna 'mniejsze'

In [408]:
macierz13 < macierz14

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

      lub

In [409]:
np.less(macierz13, macierz14)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

14) Operacja logiczna 'mniejsze i rowne'

In [410]:
macierz13 <= macierz14

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

      lub

In [411]:
np.less_equal(macierz13, macierz14)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

15) Operacja logiczna 'rowne'

In [412]:
macierz15 = np.array([[1, 2, 3, 4],
                      [3, 4, 5, 6]])
macierz15

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [413]:
macierz16 = np.array([[1, 3, 3, 5],
                      [3, 5, 5, 7]])
macierz16

array([[1, 3, 3, 5],
       [3, 5, 5, 7]])

In [414]:
macierz15 == macierz16

array([[ True, False,  True, False],
       [ True, False,  True, False]])

      lub

In [415]:
np.equal(macierz15, macierz16)

array([[ True, False,  True, False],
       [ True, False,  True, False]])

16) Operacja logiczna 'nierówna się'

In [416]:
macierz15

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [417]:
macierz16

array([[1, 3, 3, 5],
       [3, 5, 5, 7]])

In [418]:
macierz15 != macierz16

array([[False,  True, False,  True],
       [False,  True, False,  True]])

      lub

In [419]:
np.not_equal(macierz15, macierz16)

array([[False,  True, False,  True],
       [False,  True, False,  True]])

17) Stworzenie maski na macierzy

In [420]:
macierz16

array([[1, 3, 3, 5],
       [3, 5, 5, 7]])

In [421]:
np.ma.array(macierz16, mask = [[False,  True, False,  True],
                              [False,  True, False,  True]])                    # tam gdzie jest True w wyniku obliczeń wartość będzie niewidoczna

masked_array(
  data=[[1, --, 3, --],
        [3, --, 5, --]],
  mask=[[False,  True, False,  True],
        [False,  True, False,  True]],
  fill_value=999999)

18) Kopiowanie elementów jednego array i zastepowanie w drugim arrayu

In [422]:
wektor = np.array([1, 2, 3, 4, 5, 6])
wektor

array([1, 2, 3, 4, 5, 6])

In [423]:
wektor1 = np.array([7, 8, 9, 10, 11, 12])
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [424]:
np.copyto(wektor, wektor1)
wektor                                                                          # skopowiano wartości z wektor1 i zamieniono istniejace elementy w 'wektor' na te skopiowane

array([ 7,  8,  9, 10, 11, 12])

19) Zmiana wymiarów arrayu

In [425]:
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [426]:
np.reshape(wektor1, (2,3))                                                      # z wymiarów 1x6 zrobiono array 2x3

array([[ 7,  8,  9],
       [10, 11, 12]])

20) Warunek 'where'

In [427]:
my_matrix = np.array([23, 45, 112, 150, 43, 254, 95, 8])
my_matrix[np.where(my_matrix > 100)]                                            # fajny zapis, w tym wypadku otrzymamy wartosci wieksze od 10

array([112, 150, 254])

21) Odwracanie array 'flip'

In [428]:
wektor

array([ 7,  8,  9, 10, 11, 12])

In [429]:
np.flip(wektor)                                                                 # lub wektor[::-1]

array([12, 11, 10,  9,  8,  7])

22) Wartości unikalne

In [430]:
macierz4

array([[ 0.,  5., 10.],
       [10., 15., 20.]])

In [431]:
np.unique(macierz4)

array([ 0.,  5., 10., 15., 20.])

23) Spłaszczanie macierzy '.flatten', '.ravel', '.reshape(-1)'

In [432]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [433]:
macierz2.flatten()

array([6, 6, 8, 9, 6, 6])

      lub

In [434]:
macierz2.ravel()

array([6, 6, 8, 9, 6, 6])

      lub

In [435]:
macierz2.reshape(-1)

array([6, 6, 8, 9, 6, 6])

24) Macierz transponowana 

In [436]:
macierz2                                                                        # macierz 2x3

array([[6, 6, 8],
       [9, 6, 6]])

In [437]:
macierz2.T                                                                      # macierz 3x2

array([[6, 9],
       [6, 6],
       [8, 6]])

25) Tworzenie array z takimi samymi wierszami na podstawie array jednowymiarowego 

In [438]:
x = np.array([1, 2, 3])
np.broadcast_to(x, (4, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

26) Zamiana typu wartosci na 'float'

In [439]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [440]:
np.asfarray(macierz2)

array([[6., 6., 8.],
       [9., 6., 6.]])

27) Scalanie dwóch arrayów w jeden array - 'np.concatenate'





In [441]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [442]:
macierz14

array([[0.93830768, 0.44237549, 0.66145077],
       [0.40772167, 0.89078838, 0.82076795],
       [0.43863284, 0.62568708, 0.83384832]])

In [443]:
np.concatenate((macierz2, macierz14), axis = 0)                                 # axis = 0 - dokłada wiersze

array([[6.        , 6.        , 8.        ],
       [9.        , 6.        , 6.        ],
       [0.93830768, 0.44237549, 0.66145077],
       [0.40772167, 0.89078838, 0.82076795],
       [0.43863284, 0.62568708, 0.83384832]])

In [444]:
np.concatenate((macierz2, macierz14), axis = None)                              # 'None' - działa jak flatten

array([6.        , 6.        , 8.        , 9.        , 6.        ,
       6.        , 0.93830768, 0.44237549, 0.66145077, 0.40772167,
       0.89078838, 0.82076795, 0.43863284, 0.62568708, 0.83384832])

In [445]:
np.concatenate((macierz2, macierz2), axis = 1)                                  # axis = 1 - doklada kolumny

array([[6, 6, 8, 6, 6, 8],
       [9, 6, 6, 9, 6, 6]])

27a) Funkcja 'stock'

In [446]:
np.hstack((macierz2, macierz2))

array([[6, 6, 8, 6, 6, 8],
       [9, 6, 6, 9, 6, 6]])

In [447]:
np.vstack((macierz2, macierz2))

array([[6, 6, 8],
       [9, 6, 6],
       [6, 6, 8],
       [9, 6, 6]])

28) Podział tablicy na kilka podtablic

In [448]:
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [449]:
np.split(wektor1, 2)                                                            # argument '2' - dzieli na 2 podtablice

[array([7, 8, 9]), array([10, 11, 12])]

In [450]:
np.split(wektor1, [1, 3, 5])                                                    # argument jako lista dzieli po indexie

[array([7]), array([8, 9]), array([10, 11]), array([12])]

29) Modyfikacja tablicy poprzez pwoeilenie wyjsciowej tablicy wzdłuż każdej osi

In [451]:
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [452]:
np.tile(wektor1,(2,2))                                                          # zduplikowano wektor1 razy 2 po wierszach i razy 2 po kolumnach

array([[ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12]])

30) Usuwanie całych wierszy lub kolumn z tablicy wyjściowej

In [453]:
macierz13

array([[0.98284497, 0.11144726, 0.60218667],
       [0.88458041, 0.41930201, 0.53887288],
       [0.27278745, 0.4692638 , 0.46308456]])

In [454]:
np.delete(macierz13,1,0)                                                        # Usunie 1 wiersz (pamietajac ze liczymy od 0), wiersz bo drugi argument to 0

array([[0.98284497, 0.11144726, 0.60218667],
       [0.27278745, 0.4692638 , 0.46308456]])

In [455]:
macierz13

array([[0.98284497, 0.11144726, 0.60218667],
       [0.88458041, 0.41930201, 0.53887288],
       [0.27278745, 0.4692638 , 0.46308456]])

In [456]:
np.delete(macierz13,1,1)                                                        # Usunie 1 kolumne (pamietajac ze liczymy od 0), kolumne bo drugi argument to 1

array([[0.98284497, 0.60218667],
       [0.88458041, 0.53887288],
       [0.27278745, 0.46308456]])

31) Dodawanie elementów do tablicy

In [457]:
macierz13

array([[0.98284497, 0.11144726, 0.60218667],
       [0.88458041, 0.41930201, 0.53887288],
       [0.27278745, 0.4692638 , 0.46308456]])

In [458]:
np.insert(macierz13, (1, 3), 999, 0)                                            # doda 1 i 3 wiersz z elementami '999', wiersz bo ostatni argument to 0

array([[9.82844974e-01, 1.11447263e-01, 6.02186672e-01],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [8.84580406e-01, 4.19302011e-01, 5.38872879e-01],
       [2.72787447e-01, 4.69263801e-01, 4.63084562e-01],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02]])

In [459]:
np.insert(macierz13, (1, 3), 999, 1)                                            # doda 1 i 3 kolumne z elementami '999', kolumne bo ostatni argument to 1

array([[9.82844974e-01, 9.99000000e+02, 1.11447263e-01, 6.02186672e-01,
        9.99000000e+02],
       [8.84580406e-01, 9.99000000e+02, 4.19302011e-01, 5.38872879e-01,
        9.99000000e+02],
       [2.72787447e-01, 9.99000000e+02, 4.69263801e-01, 4.63084562e-01,
        9.99000000e+02]])

In [560]:
macierz133 = [1, 2, 3]
macierz13

array([[0.98284497, 0.11144726, 0.60218667],
       [0.88458041, 0.41930201, 0.53887288],
       [0.27278745, 0.4692638 , 0.46308456]])

In [563]:
np.insert(macierz13, 2, [macierz133], axis=1)                                   # musi byc [macierz133] bo bez python potrkatuje jako liste a musi byc array, axis = 1 lub 0

array([[0.98284497, 0.11144726, 1.        , 0.60218667],
       [0.88458041, 0.41930201, 2.        , 0.53887288],
       [0.27278745, 0.4692638 , 3.        , 0.46308456]])

32) Zmiana wymiarow tablicy, oraz uzupelnienie wartości jeśli brakuje, poprzez dupllikowanie od początku tablicy wyjściowej

In [460]:
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [461]:
np.resize(wektor1,(2,4))                                                        # zrobi tablice 2x4 i doda brakujace elementy

array([[ 7,  8,  9, 10],
       [11, 12,  7,  8]])

33) Usuwanie zer na początku i końcu tablicy

In [462]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
a

array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

In [463]:
np.trim_zeros(a)

array([1, 2, 3, 0, 2, 1])

34) Przesuwanie elementów w tablicy

In [464]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [465]:
np.roll(macierz2,-2)                                                            # przesuwa wszystkie elementy o 2 w lewo

array([[8, 9, 6],
       [6, 6, 6]])

In [466]:
np.roll(macierz2,1)                                                             # przesuwa wszystkie elementy o 2 w prawo

array([[6, 6, 6],
       [8, 9, 6]])

35) Obracanie elementów tablicy o 90 stopni

In [467]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [468]:
np.rot90(macierz2,1)                                                            # obróci tablice o 90 stopni w lewo

array([[8, 6],
       [6, 6],
       [6, 9]])

In [469]:
np.rot90(macierz2,2)                                                            # obróci tablice o 2x90 stopni w lewo

array([[6, 6, 9],
       [8, 6, 6]])

36) Orzymanie przekatnej macierzy kwadratowej

In [470]:
macierz17 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
macierz17

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [471]:
np.diag(macierz17)

array([1, 5, 9])

37) Kopiowanie tablicy

In [472]:
macierz17

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [473]:
macierz18 = np.copy(macierz17)
macierz18

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

38) sortowanie tablicy

In [474]:
macierz18 = np.array([[1,4],[3,1]])
macierz18

array([[1, 4],
       [3, 1]])

In [475]:
np.sort(macierz18)                                                              # Sortuje kazdy wiersz od najmniejsze do najwiekszej wartosci

array([[1, 4],
       [1, 3]])

39) Powtarzanie elementów tablicy - 'repeat'

In [476]:
macierz18

array([[1, 4],
       [3, 1]])

In [477]:
np.repeat(macierz18, 3)                                                         # jesli nie podamy 3 argumentu 'axis' to funkcja powtórzy i zrobi splaszczenie tablicy

array([1, 1, 1, 4, 4, 4, 3, 3, 3, 1, 1, 1])

In [478]:
np.repeat(macierz18,3, axis = 0)                                                # dla axis = 0, powtórzy po wierszach

array([[1, 4],
       [1, 4],
       [1, 4],
       [3, 1],
       [3, 1],
       [3, 1]])

In [479]:
np.repeat(macierz18, 4, axis = 1)                                               # dla axis = 1, powtórzy po kolumnach

array([[1, 1, 1, 1, 4, 4, 4, 4],
       [3, 3, 3, 3, 1, 1, 1, 1]])

40) Otrzymywanie wspólnych elementów z 2 tablic

In [480]:
a = np.array([3, 1, 2, 1])
a

array([3, 1, 2, 1])

In [481]:
b = np.array([1, 3, 4, 3])
b

array([1, 3, 4, 3])

In [482]:
np.intersect1d(a, b)

array([1, 3])

41) Czy tablica zawiera wskazane elementy

In [483]:
macierz18

array([[1, 4],
       [3, 1]])

In [484]:
np.isin(macierz18, [3, 4])

array([[False,  True],
       [ True, False]])

42) Wyswietlenie elementów z 1 tablicy, których nie ma w 2 tablicy

In [485]:
a = np.array([1, 2, 3, 2, 4, 1])
a

array([1, 2, 3, 2, 4, 1])

In [486]:
b = np.array([3, 4, 5, 6])
b

array([3, 4, 5, 6])

In [487]:
np.setdiff1d(a, b)

array([1, 2])

43) Unikalne, posortowane wartości dla 2 tablic

In [488]:
a

array([1, 2, 3, 2, 4, 1])

In [489]:
b

array([3, 4, 5, 6])

In [490]:
np.setxor1d(a, b)

array([1, 2, 5, 6])

44) Wszystkie wartości, bez powtórzeń, posortowane z tablic

In [491]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

#**Dostęp do elementów**

Wektor/macierz ma swoje indeksy, należy pamiętać że liczone są od 0!

In [492]:
macierz3

array([[ 0,  3,  6,  9],
       [10, 13, 16, 19]])

In [493]:
macierz3[0][0]                                                                  # element z 0-go wiersz i 0-go kolumny

0

      lub

In [494]:
macierz3[0,0]                                                                   # element z 0-go wiersz i 0-go kolumny

0

In [495]:
macierz9

array([[0.57953902, 0.39548006, 0.84203907, 0.70618343, 0.27608973],
       [0.21293778, 0.29995869, 0.61747209, 0.72158846, 0.34174634],
       [0.31234377, 0.64084684, 0.13122441, 0.59781591, 0.65325762],
       [0.04790158, 0.09584931, 0.20034563, 0.3663862 , 0.26422151],
       [0.81840157, 0.67167492, 0.66409475, 0.3281231 , 0.8577234 ]])

In [496]:
macierz9[1]                                                                     # wyswietli 1 wiersz(liczymy od 0) lub zapis: macierz9[1,:]

array([0.21293778, 0.29995869, 0.61747209, 0.72158846, 0.34174634])

In [497]:
macierz9[:,1]                                                                   # wyswietli 1 kolumne(czyli druga bo pamietamy ze kolumna pierwsza to zerowa)

array([0.39548006, 0.29995869, 0.64084684, 0.09584931, 0.67167492])

Mogą być różne kombinacje:

In [498]:
macierz9[2:,:3]                                                                 # wyswietli macierz od 2 wiersza, ale tylko dla kolumn od 0 do 3)

array([[0.31234377, 0.64084684, 0.13122441],
       [0.04790158, 0.09584931, 0.20034563],
       [0.81840157, 0.67167492, 0.66409475]])

Można również użyć metody 'flat' którwyswietli nam element który wskażemy licząć od 0 wiersz po wierszu w sposób ciągły

In [499]:
macierz9

array([[0.57953902, 0.39548006, 0.84203907, 0.70618343, 0.27608973],
       [0.21293778, 0.29995869, 0.61747209, 0.72158846, 0.34174634],
       [0.31234377, 0.64084684, 0.13122441, 0.59781591, 0.65325762],
       [0.04790158, 0.09584931, 0.20034563, 0.3663862 , 0.26422151],
       [0.81840157, 0.67167492, 0.66409475, 0.3281231 , 0.8577234 ]])

In [500]:
macierz9.flat[9]

0.3417463395846678

Można za pomocą tej metody zamieniąć wartości elementów




In [501]:
macierz9

array([[0.57953902, 0.39548006, 0.84203907, 0.70618343, 0.27608973],
       [0.21293778, 0.29995869, 0.61747209, 0.72158846, 0.34174634],
       [0.31234377, 0.64084684, 0.13122441, 0.59781591, 0.65325762],
       [0.04790158, 0.09584931, 0.20034563, 0.3663862 , 0.26422151],
       [0.81840157, 0.67167492, 0.66409475, 0.3281231 , 0.8577234 ]])

In [502]:
macierz9.flat = 9
macierz9

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [503]:
macierz9.flat[[3, 8, 13, 18, 23]] = 4
macierz9

array([[9., 9., 9., 4., 9.],
       [9., 9., 9., 4., 9.],
       [9., 9., 9., 4., 9.],
       [9., 9., 9., 4., 9.],
       [9., 9., 9., 4., 9.]])

Można również wyświetlać elementy tylko spełniające podany warunek

In [504]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [505]:
macierz2[macierz2 % 2 == 0]

array([6, 6, 8, 6, 6])

#**Operacje na macierzach/wektorach**

1) Dodawanie - należy pamietać żeby macierze wektory były tych samych wymiarów

In [506]:
macierz10 = np.random.random((3,3))                                             # macierz 3x3
macierz11 = np.random.random((3,3))                                             # macierz 3x3

In [507]:
macierz10

array([[0.36624574, 0.30123001, 0.11963924],
       [0.12910449, 0.23052936, 0.25547937],
       [0.98114268, 0.24949765, 0.31305291]])

In [508]:
macierz11

array([[0.93602049, 0.88123763, 0.33242432],
       [0.69385071, 0.10674053, 0.21011923],
       [0.65782718, 0.84726178, 0.13230124]])

In [509]:
macierz10 + macierz11

array([[1.30226623, 1.18246764, 0.45206356],
       [0.8229552 , 0.33726989, 0.4655986 ],
       [1.63896986, 1.09675943, 0.44535414]])

      lub

In [510]:
np.add(macierz10, macierz11)

array([[1.30226623, 1.18246764, 0.45206356],
       [0.8229552 , 0.33726989, 0.4655986 ],
       [1.63896986, 1.09675943, 0.44535414]])

2) Odejmowanie

In [511]:
macierz10 - macierz11

array([[-0.56977475, -0.58000762, -0.21278508],
       [-0.56474622,  0.12378883,  0.04536014],
       [ 0.3233155 , -0.59776413,  0.18075167]])

In [512]:
np.subtract(macierz10, macierz11)

array([[-0.56977475, -0.58000762, -0.21278508],
       [-0.56474622,  0.12378883,  0.04536014],
       [ 0.3233155 , -0.59776413,  0.18075167]])

3) Mnożenie miedzy sobą

In [513]:
macierz10 * macierz11

array([[0.34281352, 0.26545522, 0.03977099],
       [0.08957924, 0.02460683, 0.05368113],
       [0.64542232, 0.21138983, 0.04141729]])

In [514]:
np.multiply(macierz10, macierz11)

array([[0.34281352, 0.26545522, 0.03977099],
       [0.08957924, 0.02460683, 0.05368113],
       [0.64542232, 0.21138983, 0.04141729]])

4) Mnożenie przez liczbę

In [515]:
macierz10 * 5

array([[1.83122869, 1.50615004, 0.59819621],
       [0.64552245, 1.15264679, 1.27739685],
       [4.90571341, 1.24748827, 1.56526453]])

In [516]:
np.multiply(macierz10, 5)

array([[1.83122869, 1.50615004, 0.59819621],
       [0.64552245, 1.15264679, 1.27739685],
       [4.90571341, 1.24748827, 1.56526453]])

In [517]:
np.exp(macierz10)

array([[1.44230963, 1.35152017, 1.12709017],
       [1.13780901, 1.25926644, 1.29108038],
       [2.66750261, 1.28338055, 1.36759388]])

In [518]:
macierz10

array([[0.36624574, 0.30123001, 0.11963924],
       [0.12910449, 0.23052936, 0.25547937],
       [0.98114268, 0.24949765, 0.31305291]])

5) Dzielenie miedzy sobą

In [519]:
macierz10 / macierz11

array([[0.39127961, 0.34182608, 0.35989919],
       [0.18606955, 2.15971718, 1.21587808],
       [1.49149004, 0.29447528, 2.36621297]])

In [520]:
np.divide(macierz10, macierz11)

array([[0.39127961, 0.34182608, 0.35989919],
       [0.18606955, 2.15971718, 1.21587808],
       [1.49149004, 0.29447528, 2.36621297]])

6) Transpozycja macierzy czyli zamiana wierszy na kolumny i odwrotnie

In [521]:
macierz10

array([[0.36624574, 0.30123001, 0.11963924],
       [0.12910449, 0.23052936, 0.25547937],
       [0.98114268, 0.24949765, 0.31305291]])

In [522]:
macierz10.T

array([[0.36624574, 0.12910449, 0.98114268],
       [0.30123001, 0.23052936, 0.24949765],
       [0.11963924, 0.25547937, 0.31305291]])

7) Macierz odwrotna - macierz musi byc kwadratowa, a wyznacznik niezerowy

In [523]:
np.linalg.inv(macierz10)

array([[ 0.19500209, -1.49152072,  1.14269143],
       [ 4.86546331, -0.06315123, -1.80789412],
       [-4.48884687,  4.72492252,  1.05388578]])

8) Do sprawdzenia 
  * np.exp()
  * np.sqrt()
  * np.sin()
  * np.cos()
  * np.log()

#**Liczby losowe**

1) Losowa liczba z rozkładu normalnego (Gaussa)

In [524]:
np.random.normal()

0.7813151687271424

2) Losowy array z rozkładu normlanego

In [525]:
np.random.normal(size=4)                                                        # 4 elementy z rozkladu normalengo

array([ 0.12497299, -0.25689491,  0.46505408,  0.77442244])

3) Losowy zestaw licz z układu jednolitego

In [526]:
np.random.uniform(size=6)

array([0.38855948, 0.41148337, 0.57269079, 0.16621392, 0.54913947,
       0.64928574])

      lub z przedziału

In [527]:
np.random.uniform(3, 30, size = 5)

array([13.11665329, 23.38783633,  7.6066675 , 27.11917743, 26.13672681])

4) Losowa liczba zmiennoprzecinkowa

In [528]:
np.random.random()                                                              # z przedzialu od 0 (wlacznie) do 1 (przedzial otwarty)

0.5861491689605052

      lub zestaw

In [529]:
np.random.random(size = 4)

array([0.67627222, 0.05326581, 0.1077408 , 0.67154622])

      lub array 2-wymiarowy

In [530]:
np.random.random((2,3))                                                         # stworzy macierz dwuwymiarową w tym przypadku 2x3 z elementami losowymi

array([[0.38461576, 0.98903393, 0.98389906],
       [0.06071391, 0.72185394, 0.58416496]])

5) Losowa liczba calkowita

In [531]:
np.random.randint(10,20)                                                        # trzeba podac zakres

12

      lub zestaw

In [532]:
np.random.randint(1, 11, size=5)

array([ 3, 10,  7,  3,  5])

In [533]:
np.random.randint([2, 3, 10], 20)                           # wygeneruje macierz 1x3 gdzie lista w tym przypadku [2, 3, 10] to dolny granica przedziału, a 20 górna granica. 
                                                            # Jeśli chcemy wiekszą macierz to dodajemy liczby w zakresie

array([10,  3, 11])

In [534]:
np.random.randint([2, 3, 10, 15], 20)

array([ 7,  5, 16, 19])

In [535]:
np.random.randint(7, [20, 30, 10])                         # wygeneruje macierz 1x3 gdzie lista w tym przypadku [20, 30, 10] to górna granica przedziału, a 7 dolna granica. 
                                                           # Jeśli chcemy wiekszą macierz to dodajemy liczby w zakresie

array([15, 23,  8])

In [536]:
np.random.randint(1, 5, size=(2, 4))                                            # stworzy macierz 2x4, z losowymi elementami z przedzialu od 1 do 5

array([[2, 3, 3, 3],
       [3, 2, 4, 4]])

6) Losowy element z tablicy 2D

In [537]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [538]:
i,j = np.where(macierz2)

In [539]:
macierz2[np.random.choice((i), 3), np.random.choice((j), 3)]

array([8, 6, 8])

# ***STATYSTYKA***

1) Różnica max - min wartośći dla tablicy (lub kazdego wiersza/kolumny)

In [540]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [541]:
np.ptp(macierz2)                                                                # max = 9, min = 5, 9 - 5 = 4

3

In [542]:
np.ptp(macierz2, axis = 0)                                                      # różnica dla kazdej kolumny bo drugi argument to 0

array([3, 0, 2])

In [543]:
np.ptp(macierz2, axis = 1)                                                      # różnica dla kazdego wiersza bo drugi argument to 1

array([2, 3])

2) Mediana

In [544]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [545]:
np.median(macierz2)                                                             # mediana dla calej tablicy

6.0

In [546]:
np.median(macierz2, axis = 0)                                                   # mediana dla kazdej kolumny bo drugi argument to 0

array([7.5, 6. , 7. ])

In [547]:
np.median(macierz2, axis = 1)                                                   # mediana dla kazdego wiersza bo drugi argument to 1

array([6., 6.])

3) średnia

In [548]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [549]:
np.mean(macierz2)                                                               # średnia dla calej tablicy

6.833333333333333

In [550]:
np.mean(macierz2, axis = 0)                                                     # średnia dla kazdej kolumny bo drugi argument to 0

array([7.5, 6. , 7. ])

In [551]:
np.mean(macierz2, axis = 1)                                                     # średnia dla kazdego wiersza bo drugi argument to 1

array([6.66666667, 7.        ])

4) Odchylenie standardowe

In [552]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [553]:
np.std(macierz2)

1.2133516482134197

5) Wariancja

In [554]:
macierz2

array([[6, 6, 8],
       [9, 6, 6]])

In [555]:
np.var(macierz2)

1.4722222222222223