<a href="https://colab.research.google.com/github/Patstach/DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

Biblioteka

In [2]:
import numpy as np

* Sklara czyli pojedyncza cyfra jest 0-wymiarowym tensorem (0D)
* Wektor to tensor 1-wymiarowy (1D)
* Macierz to tensor 2-wymiarowy (2D)
* Wystepuje też macierz 3-wymiarowa, jest to tensor (3D)

#**WEKTOR**

In [3]:
df = np.array([[1,2,3],[4,5,6]]) 
df

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.shape(df)

(2, 3)

1) Tworzenie wektorów, czyli tensora 1-wymiarowego (1D)

  * poprzez uzycie listy:

In [5]:
wektor = np.array([1, 2, 3, 4, 5, 6])
wektor

array([1, 2, 3, 4, 5, 6])

      lub:

In [6]:
mylist = [1, 2, 3, 4, 5]                                                        # Tworzymy wczesniej liste
mylist

[1, 2, 3, 4, 5]

In [7]:
wektor2 = np.array(mylist)                                                      # Tworzymy wektor z wczesniejszej listy
wektor2

array([1, 2, 3, 4, 5])

2) Tworzenie wektora w sytuacji w której wiemy jakie maja być wartości - ciąg liczbowy

In [8]:
wektor3 = np.arange(2,8,2)
wektor3                                                                         # podajemy wartość początkową (np.2), końcową (np.8), z przeskokiem co 2.

array([2, 4, 6])

3) Tworzenie wektora, jeśli chcemy stworzyć wartości w RÓWNYCH odstepach

In [9]:
wektor4 = np.linspace(0, 10, 3)                                                 # stworzy wektor z 3 elementami (ostatni argument), pierwszy to poczatek przedzialu, 
wektor4                                                                         #  drugi to koniec przedziału

array([ 0.,  5., 10.])

4) Zerowy wektor

In [10]:
wektor5 = np.zeros(4)                                                           # wektor zerowy z 4 elementami
wektor5

array([0., 0., 0., 0.])

5) Jedynkowy wektor

In [11]:
wektor6 = np.ones(5)                                                            # wektor jedynkowy z 5 elementami
wektor6

array([1., 1., 1., 1., 1.])

6) Wektor ze stałą wartością

In [12]:
wektor7 = np.full((5),7)                                                        # wektor z 5 elementami i stałą wrtością elementów (7)
wektor7

array([7, 7, 7, 7, 7])

7) Wektor pusty - Należy używać ostrożnie

In [13]:
wektor8 = np.empty((3))                                                         # Tworzy 'pusty' wektor który należy samemu uzupełnić?
wektor8

array([ 0.,  5., 10.])

8) Wektor z losowymi wartościami

In [14]:
wektor9 = np.random.random(5)                                                   # wektor z 5 losowymi elementami
wektor9

array([0.27476184, 0.82907943, 0.74304952, 0.4952069 , 0.18474421])

#**MACIERZ**

Macierz jest 2-wymiarowym tensorem, wiekszosc procedur jest wykonywana analogiczne do wektora. Należy podawać jedynie argumenty dla '2-go wymiaru'
np.

In [15]:
macierz = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10]])
macierz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
macierz2 = np.array([np.random.randint(3, 10, size=3),
                     np.random.randint(3,10, size=3)])
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [17]:
macierz3 = np.array([np.arange(0, 10, 3),
                    np.arange(10, 20, 3)])
macierz3

array([[ 0,  3,  6,  9],
       [10, 13, 16, 19]])

In [18]:
macierz4 = np.array([np.linspace(0, 10, 3),
                    np.linspace(10, 20, 3)])
macierz4

array([[ 0.,  5., 10.],
       [10., 15., 20.]])

In [19]:
macierz5 = np.zeros((4,4))                                                      # macierz zerowa 4x4
macierz5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
macierz6 = np.ones((5,5))                                                       # macierz jedynkowa 4x4
macierz6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
macierz7 = np.full((5,4),7)                                                     # macierz 5x4 ze stałą wrtością elementów (7)
macierz7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [22]:
macierz9 = np.random.random((5,5))                                              # macierz 5x5 z losową wartościa elementów                  
macierz9

array([[0.41150122, 0.42509761, 0.8850055 , 0.69167055, 0.74266158],
       [0.76296918, 0.06539807, 0.76579257, 0.71309467, 0.95559277],
       [0.67480664, 0.92405208, 0.715767  , 0.6274011 , 0.07732449],
       [0.87832953, 0.24445271, 0.47910888, 0.99343768, 0.89706667],
       [0.58782477, 0.00429302, 0.19372607, 0.06128244, 0.74677324]])

In [23]:
macierz10 = np.identity(3)                                                      # macierz kwadratowa jednostkowa 3x3
macierz10

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
macierz11 = np.eye(3,4)                                                         # macierz 2D z przekątną z '1', reszta elementow '0', nie musi być kwadratowa
macierz11

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [25]:
macierz12 = np.eye(4, 5, k = 2)                                                 # można przesuwać przekątną z 1 za pomocą parametru k, jeżeli k>0 to przesuwamy po kolumnach
macierz12

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [26]:
macierz12 = np.eye(4, 5, k = -2)                                                 # można przesuwać przekątną z 1 za pomocą parametru k, jeżeli k<0 to przesuwamy po wierszach
macierz12

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

#**Atrybuty NUMPY**

1) Jesli chcemy dowiedzieć sie o skaldni danego atrybutu możemy to z robić za pomocą atrybutu. np

In [27]:
np.info(np.arange)                                                              # w tym przypadku wyrzuci nam instrukcję dotyczącą atrybutu 'arange'

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`. See the warnings section below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
    between t

2) Ilość wierszy i kolumn

In [28]:
macierz9.shape                                                           # na podstawie wczesniej stworzonej zmiennej 'macierz9' - 5 wierszy i 5 kolumn (macierz-> 2 wymiary)

(5, 5)

In [29]:
wektor7.shape                                                                   # na podstawie wczesniej stworzonej zmiennej 'wektor7' - 5 elementów (wektor-> 1 wymiar)

(5,)

3) Ilość elementów macierzy/wektora

In [30]:
macierz7.size                                                                   # na podstawie wczesniej stworzonej zmiennej 'macierz7'

20

In [31]:
wektor3.size                                                                    # na podstawie wczesniej stworzonej zmiennej 'wektor3'

3

4) Ilość wymiarów - sprawdzamy czy jest to wektor, macierz 2D, macierz 3D

In [32]:
macierz4.ndim                                                                   # na podstawie wczesniej stworzonej zmiennej 'macierz4' -> 2 wymiary bo macierz

2

In [33]:
wektor2.ndim                                                                    # na podstawie wczesniej stworzonej zmiennej 'wektor2' -> 1 wymiar bo wektor

1

5) Typ elementów macierzy/wektora (int64, float32, complex, bool, object, string, unicode)



In [34]:
macierz7.dtype

dtype('int64')

In [35]:
wektor3.dtype

dtype('int64')

6) Zmiana typu elementów

In [36]:
macierz7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [37]:
macierz7.dtype

dtype('int64')

In [38]:
macierz7.astype(str)                                                            # zamiana elementów na 'str'

array([['7', '7', '7', '7'],
       ['7', '7', '7', '7'],
       ['7', '7', '7', '7'],
       ['7', '7', '7', '7'],
       ['7', '7', '7', '7']], dtype='<U21')

7) Sprawdzenie czy aarray zawiera element NaN

In [39]:
macierz12 = np.array([[1, 2, 4, np.nan],
                     [3, np.nan, 6, 7]])
macierz12

array([[ 1.,  2.,  4., nan],
       [ 3., nan,  6.,  7.]])

In [40]:
np.isnan(macierz12)

array([[False, False, False,  True],
       [False,  True, False, False]])

8) Operacja logiczna 'and'

In [41]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [42]:
np.logical_and(x > 1, x < 4)

array([False, False,  True,  True, False])

9) Operacja logiczna 'lub'

In [43]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [44]:
np.logical_or(x > 1, x < 4)

array([ True,  True,  True,  True,  True])

10) Zaprzeczenie logiczne

In [45]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [46]:
np.logical_not(x < 3)                                                           # jeśli warunek jest True, to metoda zwraca nam False i odwrotnie

array([False, False, False,  True,  True])

11) Operacja logiczna 'wieksze'

In [47]:
macierz13 = np.random.random((3,3))            
macierz13

array([[0.11174765, 0.79127036, 0.30881042],
       [0.20083941, 0.00212951, 0.95219964],
       [0.79689646, 0.03188961, 0.74096449]])

In [48]:
macierz14 = np.random.random((3,3))            
macierz14

array([[0.75844951, 0.23326235, 0.36478079],
       [0.7137344 , 0.70409249, 0.56610314],
       [0.82664483, 0.01272024, 0.06077753]])

In [49]:
macierz13 > macierz14

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True]])

      lub

In [50]:
np.greater(macierz13, macierz14)

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True]])

12) Operacja logiczna 'wieksze i rowne'

In [51]:
macierz13 >= macierz14

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True]])

      lub

In [52]:
np.greater_equal(macierz13, macierz14)

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True]])

13) Operacja logiczna 'mniejsze'

In [53]:
macierz13 < macierz14

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

      lub

In [54]:
np.less(macierz13, macierz14)

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

14) Operacja logiczna 'mniejsze i rowne'

In [55]:
macierz13 <= macierz14

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

      lub

In [56]:
np.less_equal(macierz13, macierz14)

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

15) Operacja logiczna 'rowne'

In [57]:
macierz15 = np.array([[1, 2, 3, 4],
                      [3, 4, 5, 6]])
macierz15

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [58]:
macierz16 = np.array([[1, 3, 3, 5],
                      [3, 5, 5, 7]])
macierz16

array([[1, 3, 3, 5],
       [3, 5, 5, 7]])

In [59]:
macierz15 == macierz16

array([[ True, False,  True, False],
       [ True, False,  True, False]])

      lub

In [60]:
np.equal(macierz15, macierz16)

array([[ True, False,  True, False],
       [ True, False,  True, False]])

16) Operacja logiczna 'nierówna się'

In [61]:
macierz15

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [62]:
macierz16

array([[1, 3, 3, 5],
       [3, 5, 5, 7]])

In [63]:
macierz15 != macierz16

array([[False,  True, False,  True],
       [False,  True, False,  True]])

      lub

In [64]:
np.not_equal(macierz15, macierz16)

array([[False,  True, False,  True],
       [False,  True, False,  True]])

17) Stworzenie maski na macierzy

In [65]:
macierz16

array([[1, 3, 3, 5],
       [3, 5, 5, 7]])

In [66]:
np.ma.array(macierz16, mask = [[False,  True, False,  True],
                              [False,  True, False,  True]])                    # tam gdzie jest True w wyniku obliczeń wartość będzie niewidoczna

masked_array(
  data=[[1, --, 3, --],
        [3, --, 5, --]],
  mask=[[False,  True, False,  True],
        [False,  True, False,  True]],
  fill_value=999999)

18) Kopiowanie elementów jednego array i zastepowanie w drugim arrayu

In [67]:
wektor = np.array([1, 2, 3, 4, 5, 6])
wektor

array([1, 2, 3, 4, 5, 6])

In [68]:
wektor1 = np.array([7, 8, 9, 10, 11, 12])
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [69]:
np.copyto(wektor, wektor1)
wektor                                                                          # skopowiano wartości z wektor1 i zamieniono istniejace elementy w 'wektor' na te skopiowane

array([ 7,  8,  9, 10, 11, 12])

19) Zmiana wymiarów arrayu

In [70]:
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [71]:
np.reshape(wektor1, (2,3))                                                      # z wymiarów 1x6 zrobiono array 2x3

array([[ 7,  8,  9],
       [10, 11, 12]])

20) Warunek 'where'

In [72]:
my_matrix = np.array([23, 45, 112, 150, 43, 254, 95, 8])
my_matrix[np.where(my_matrix > 100)]                                            # fajny zapis, w tym wypadku otrzymamy wartosci wieksze od 10

array([112, 150, 254])

21) Odwracanie array 'flip'

In [73]:
wektor

array([ 7,  8,  9, 10, 11, 12])

In [74]:
np.flip(wektor)                                                                 # lub wektor[::-1]

array([12, 11, 10,  9,  8,  7])

22) Wartości unikalne

In [75]:
macierz4

array([[ 0.,  5., 10.],
       [10., 15., 20.]])

In [76]:
np.unique(macierz4)

array([ 0.,  5., 10., 15., 20.])

23) Spłaszczanie macierzy '.flatten', '.ravel', '.reshape(-1)'

In [77]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [78]:
macierz2.flatten()

array([9, 5, 8, 8, 5, 9])

      lub

In [79]:
macierz2.ravel()

array([9, 5, 8, 8, 5, 9])

      lub

In [80]:
macierz2.reshape(-1)

array([9, 5, 8, 8, 5, 9])

24) Macierz transponowana 

In [81]:
macierz2                                                                        # macierz 2x3

array([[9, 5, 8],
       [8, 5, 9]])

In [82]:
macierz2.T                                                                      # macierz 3x2

array([[9, 8],
       [5, 5],
       [8, 9]])

25) Tworzenie array z takimi samymi wierszami na podstawie array jednowymiarowego 

In [83]:
x = np.array([1, 2, 3])
np.broadcast_to(x, (4, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

26) Zamiana typu wartosci na 'float'

In [84]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [85]:
np.asfarray(macierz2)

array([[9., 5., 8.],
       [8., 5., 9.]])

27) Scalanie dwóch arrayów w jeden array - 'np.concatenate'





In [86]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [87]:
macierz14

array([[0.75844951, 0.23326235, 0.36478079],
       [0.7137344 , 0.70409249, 0.56610314],
       [0.82664483, 0.01272024, 0.06077753]])

In [88]:
np.concatenate((macierz2, macierz14), axis = 0)                                 # axis = 0 - dokłada wiersze

array([[9.        , 5.        , 8.        ],
       [8.        , 5.        , 9.        ],
       [0.75844951, 0.23326235, 0.36478079],
       [0.7137344 , 0.70409249, 0.56610314],
       [0.82664483, 0.01272024, 0.06077753]])

In [89]:
np.concatenate((macierz2, macierz14), axis = None)                              # 'None' - działa jak flatten

array([9.        , 5.        , 8.        , 8.        , 5.        ,
       9.        , 0.75844951, 0.23326235, 0.36478079, 0.7137344 ,
       0.70409249, 0.56610314, 0.82664483, 0.01272024, 0.06077753])

In [90]:
np.concatenate((macierz2, macierz2), axis = 1)                                  # axis = 1 - doklada kolumny

array([[9, 5, 8, 9, 5, 8],
       [8, 5, 9, 8, 5, 9]])

28) Podział tablicy na kilka podtablic

In [91]:
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [92]:
np.split(wektor1, 2)                                                            # argument '2' - dzieli na 2 podtablice

[array([7, 8, 9]), array([10, 11, 12])]

In [93]:
np.split(wektor1, [1, 3, 5])                                                    # argument jako lista dzieli po indexie

[array([7]), array([8, 9]), array([10, 11]), array([12])]

29) Modyfikacja tablicy poprzez pwoeilenie wyjsciowej tablicy wzdłuż każdej osi

In [94]:
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [95]:
np.tile(wektor1,(2,2))                                                          # zduplikowano wektor1 razy 2 po wierszach i razy 2 po kolumnach

array([[ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 12,  7,  8,  9, 10, 11, 12]])

30) Usuwanie całych wierszy lub kolumn z tablicy wyjściowej

In [96]:
macierz13

array([[0.11174765, 0.79127036, 0.30881042],
       [0.20083941, 0.00212951, 0.95219964],
       [0.79689646, 0.03188961, 0.74096449]])

In [97]:
np.delete(macierz13,1,0)                                                        # Usunie 1 wiersz (pamietajac ze liczymy od 0), wiersz bo drugi argument to 0

array([[0.11174765, 0.79127036, 0.30881042],
       [0.79689646, 0.03188961, 0.74096449]])

In [98]:
macierz13

array([[0.11174765, 0.79127036, 0.30881042],
       [0.20083941, 0.00212951, 0.95219964],
       [0.79689646, 0.03188961, 0.74096449]])

In [99]:
np.delete(macierz13,1,1)                                                        # Usunie 1 kolumne (pamietajac ze liczymy od 0), kolumne bo drugi argument to 1

array([[0.11174765, 0.30881042],
       [0.20083941, 0.95219964],
       [0.79689646, 0.74096449]])

31) Dodawanie elementów do tablicy

In [100]:
macierz13

array([[0.11174765, 0.79127036, 0.30881042],
       [0.20083941, 0.00212951, 0.95219964],
       [0.79689646, 0.03188961, 0.74096449]])

In [101]:
np.insert(macierz13, (1, 3), 999, 0)                                            # doda 1 i 3 wiersz z elementami '999', wiersz bo ostatni argument to 0

array([[1.11747649e-01, 7.91270361e-01, 3.08810420e-01],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [2.00839411e-01, 2.12950553e-03, 9.52199641e-01],
       [7.96896458e-01, 3.18896054e-02, 7.40964491e-01],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02]])

In [102]:
np.insert(macierz13, (1, 3), 999, 1)                                            # doda 1 i 3 kolumne z elementami '999', kolumne bo ostatni argument to 1

array([[1.11747649e-01, 9.99000000e+02, 7.91270361e-01, 3.08810420e-01,
        9.99000000e+02],
       [2.00839411e-01, 9.99000000e+02, 2.12950553e-03, 9.52199641e-01,
        9.99000000e+02],
       [7.96896458e-01, 9.99000000e+02, 3.18896054e-02, 7.40964491e-01,
        9.99000000e+02]])

32) Zmiana wymiarow tablicy, oraz uzupelnienie wartości jeśli brakuje, poprzez dupllikowanie od początku tablicy wyjściowej

In [103]:
wektor1

array([ 7,  8,  9, 10, 11, 12])

In [104]:
np.resize(wektor1,(2,4))                                                        # zrobi tablice 2x4 i doda brakujace elementy

array([[ 7,  8,  9, 10],
       [11, 12,  7,  8]])

33) Usuwanie zer na początku i końcu tablicy

In [105]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
a

array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

In [106]:
np.trim_zeros(a)

array([1, 2, 3, 0, 2, 1])

34) Przesuwanie elementów w tablicy

In [107]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [108]:
np.roll(macierz2,-2)                                                            # przesuwa wszystkie elementy o 2 w lewo

array([[8, 8, 5],
       [9, 9, 5]])

In [109]:
np.roll(macierz2,1)                                                             # przesuwa wszystkie elementy o 2 w prawo

array([[9, 9, 5],
       [8, 8, 5]])

35) Obracanie elementów tablicy o 90 stopni

In [110]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [111]:
np.rot90(macierz2,1)                                                            # obróci tablice o 90 stopni w lewo

array([[8, 9],
       [5, 5],
       [9, 8]])

In [112]:
np.rot90(macierz2,2)                                                            # obróci tablice o 2x90 stopni w lewo

array([[9, 5, 8],
       [8, 5, 9]])

36) Orzymanie przekatnej macierzy kwadratowej

In [113]:
macierz17 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
macierz17

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
np.diag(macierz17)

array([1, 5, 9])

37) Kopiowanie tablicy

In [115]:
macierz17

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
macierz18 = np.copy(macierz17)
macierz18

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

38) sortowanie tablicy

In [117]:
macierz18 = np.array([[1,4],[3,1]])
macierz18

array([[1, 4],
       [3, 1]])

In [118]:
np.sort(macierz18)                                                              # Sortuje kazdy wiersz od najmniejsze do najwiekszej wartosci

array([[1, 4],
       [1, 3]])

39) Powtarzanie elementów tablicy - 'repeat'

In [179]:
macierz18

array([[1, 4],
       [3, 1]])

In [183]:
np.repeat(macierz18, 3)                                                         # jesli nie podamy 3 argumentu 'axis' to funkcja powtórzy i zrobi splaszczenie tablicy

array([1, 1, 1, 4, 4, 4, 3, 3, 3, 1, 1, 1])

In [184]:
np.repeat(macierz18,3, axis = 0)                                                # dla axis = 0, powtórzy po wierszach

array([[1, 4],
       [1, 4],
       [1, 4],
       [3, 1],
       [3, 1],
       [3, 1]])

In [186]:
np.repeat(macierz18, 4, axis = 1)                                               # dla axis = 1, powtórzy po kolumnach

array([[1, 1, 1, 1, 4, 4, 4, 4],
       [3, 3, 3, 3, 1, 1, 1, 1]])

#**Dostęp do elementów**

Wektor/macierz ma swoje indeksy, należy pamiętać że liczone są od 0!

In [120]:
macierz3

array([[ 0,  3,  6,  9],
       [10, 13, 16, 19]])

In [121]:
macierz3[0][0]                                                                  # element z 0-go wiersz i 0-go kolumny

0

      lub

In [122]:
macierz3[0,0]                                                                   # element z 0-go wiersz i 0-go kolumny

0

In [123]:
macierz9

array([[0.41150122, 0.42509761, 0.8850055 , 0.69167055, 0.74266158],
       [0.76296918, 0.06539807, 0.76579257, 0.71309467, 0.95559277],
       [0.67480664, 0.92405208, 0.715767  , 0.6274011 , 0.07732449],
       [0.87832953, 0.24445271, 0.47910888, 0.99343768, 0.89706667],
       [0.58782477, 0.00429302, 0.19372607, 0.06128244, 0.74677324]])

In [124]:
macierz9[1]                                                                     # wyswietli 1 wiersz(liczymy od 0) lub zapis: macierz9[1,:]

array([0.76296918, 0.06539807, 0.76579257, 0.71309467, 0.95559277])

In [125]:
macierz9[:,1]                                                                   # wyswietli 1 kolumne(czyli druga bo pamietamy ze kolumna pierwsza to zerowa)

array([0.42509761, 0.06539807, 0.92405208, 0.24445271, 0.00429302])

Mogą być różne kombinacje:

In [126]:
macierz9[2:,:3]                                                                 # wyswietli macierz od 2 wiersza, ale tylko dla kolumn od 0 do 3)

array([[0.67480664, 0.92405208, 0.715767  ],
       [0.87832953, 0.24445271, 0.47910888],
       [0.58782477, 0.00429302, 0.19372607]])

Można również użyć metody 'flat' którwyswietli nam element który wskażemy licząć od 0 wiersz po wierszu w sposób ciągły

In [127]:
macierz9

array([[0.41150122, 0.42509761, 0.8850055 , 0.69167055, 0.74266158],
       [0.76296918, 0.06539807, 0.76579257, 0.71309467, 0.95559277],
       [0.67480664, 0.92405208, 0.715767  , 0.6274011 , 0.07732449],
       [0.87832953, 0.24445271, 0.47910888, 0.99343768, 0.89706667],
       [0.58782477, 0.00429302, 0.19372607, 0.06128244, 0.74677324]])

In [128]:
macierz9.flat[9]

0.9555927747896228

Można za pomocą tej metody zamieniąć wartości elementów




In [129]:
macierz9

array([[0.41150122, 0.42509761, 0.8850055 , 0.69167055, 0.74266158],
       [0.76296918, 0.06539807, 0.76579257, 0.71309467, 0.95559277],
       [0.67480664, 0.92405208, 0.715767  , 0.6274011 , 0.07732449],
       [0.87832953, 0.24445271, 0.47910888, 0.99343768, 0.89706667],
       [0.58782477, 0.00429302, 0.19372607, 0.06128244, 0.74677324]])

In [130]:
macierz9.flat = 9
macierz9

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [131]:
macierz9.flat[[3, 8, 13, 18, 23]] = 4
macierz9

array([[9., 9., 9., 4., 9.],
       [9., 9., 9., 4., 9.],
       [9., 9., 9., 4., 9.],
       [9., 9., 9., 4., 9.],
       [9., 9., 9., 4., 9.]])

Można również wyświetlać elementy tylko spełniające podany warunek

In [187]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [194]:
macierz2[macierz2 % 2 == 0]

array([8, 8])

#**Operacje na macierzach/wektorach**

1) Dodawanie - należy pamietać żeby macierze wektory były tych samych wymiarów

In [132]:
macierz10 = np.random.random((3,3))                                             # macierz 3x3
macierz11 = np.random.random((3,3))                                             # macierz 3x3

In [133]:
macierz10

array([[0.54545807, 0.37039319, 0.64493252],
       [0.65274105, 0.89700409, 0.39628136],
       [0.3726587 , 0.25083959, 0.41603753]])

In [134]:
macierz11

array([[0.78319583, 0.43680837, 0.29809359],
       [0.29815416, 0.21589895, 0.93818377],
       [0.9424727 , 0.1153501 , 0.80431824]])

In [135]:
macierz10 + macierz11

array([[1.3286539 , 0.80720156, 0.94302611],
       [0.95089521, 1.11290303, 1.33446513],
       [1.3151314 , 0.36618969, 1.22035578]])

      lub

In [136]:
np.add(macierz10, macierz11)

array([[1.3286539 , 0.80720156, 0.94302611],
       [0.95089521, 1.11290303, 1.33446513],
       [1.3151314 , 0.36618969, 1.22035578]])

2) Odejmowanie

In [137]:
macierz10 - macierz11

array([[-0.23773776, -0.06641518,  0.34683893],
       [ 0.35458689,  0.68110514, -0.54190241],
       [-0.569814  ,  0.13548949, -0.38828071]])

In [138]:
np.subtract(macierz10, macierz11)

array([[-0.23773776, -0.06641518,  0.34683893],
       [ 0.35458689,  0.68110514, -0.54190241],
       [-0.569814  ,  0.13548949, -0.38828071]])

3) Mnożenie miedzy sobą

In [139]:
macierz10 * macierz11

array([[0.42720049, 0.16179085, 0.19225025],
       [0.19461746, 0.19366224, 0.37178474],
       [0.35122065, 0.02893437, 0.33462658]])

In [140]:
np.multiply(macierz10, macierz11)

array([[0.42720049, 0.16179085, 0.19225025],
       [0.19461746, 0.19366224, 0.37178474],
       [0.35122065, 0.02893437, 0.33462658]])

4) Mnożenie przez liczbę

In [141]:
macierz10 * 5

array([[2.72729035, 1.85196595, 3.2246626 ],
       [3.26370524, 4.48502044, 1.98140679],
       [1.86329351, 1.25419793, 2.08018766]])

In [142]:
np.multiply(macierz10, 5)

array([[2.72729035, 1.85196595, 3.2246626 ],
       [3.26370524, 4.48502044, 1.98140679],
       [1.86329351, 1.25419793, 2.08018766]])

In [143]:
np.exp(macierz10)

array([[1.72539855, 1.44830396, 1.90585842],
       [1.92079862, 2.45224538, 1.48628744],
       [1.45158883, 1.28510392, 1.51594276]])

In [144]:
macierz10

array([[0.54545807, 0.37039319, 0.64493252],
       [0.65274105, 0.89700409, 0.39628136],
       [0.3726587 , 0.25083959, 0.41603753]])

5) Dzielenie miedzy sobą

In [145]:
macierz10 / macierz11

array([[0.6964517 , 0.84795351, 2.16352364],
       [2.18927367, 4.15474048, 0.42239204],
       [0.3954053 , 2.17459356, 0.51725487]])

In [146]:
np.divide(macierz10, macierz11)

array([[0.6964517 , 0.84795351, 2.16352364],
       [2.18927367, 4.15474048, 0.42239204],
       [0.3954053 , 2.17459356, 0.51725487]])

6) Transpozycja macierzy czyli zamiana wierszy na kolumny i odwrotnie

In [147]:
macierz10

array([[0.54545807, 0.37039319, 0.64493252],
       [0.65274105, 0.89700409, 0.39628136],
       [0.3726587 , 0.25083959, 0.41603753]])

In [148]:
macierz10.T

array([[0.54545807, 0.65274105, 0.3726587 ],
       [0.37039319, 0.89700409, 0.25083959],
       [0.64493252, 0.39628136, 0.41603753]])

7) Macierz odwrotna - macierz musi byc kwadratowa, a wyznacznik niezerowy

In [149]:
np.linalg.inv(macierz10)

array([[-41.87682929,  -1.17426081,  66.03506802],
       [ 18.9492156 ,   2.05093295, -31.32821168],
       [ 26.08551051,  -0.18473493, -37.85761096]])

8) Do sprawdzenia 
  * np.exp()
  * np.sqrt()
  * np.sin()
  * np.cos()
  * np.log()

#**Liczby losowe**

1) Losowa liczba z rozkładu normalnego (Gaussa)

In [150]:
np.random.normal()

0.6158380055938681

2) Losowy array z rozkładu normlanego

In [151]:
np.random.normal(size=4)                                                        # 4 elementy z rozkladu normalengo

array([ 0.66539389, -0.67225726, -0.46542724,  1.19212646])

3) Losowy zestaw licz z układu jednolitego

In [152]:
np.random.uniform(size=6)

array([0.59933126, 0.40322162, 0.18696778, 0.12296284, 0.94948072,
       0.36535054])

      lub z przedziału

In [153]:
np.random.uniform(3, 30, size = 5)

array([20.96354382,  7.97317075, 25.72470391, 29.03911783,  4.42019454])

4) Losowa liczba zmiennoprzecinkowa

In [154]:
np.random.random()                                                              # z przedzialu od 0 (wlacznie) do 1 (przedzial otwarty)

0.05228883251593697

      lub zestaw

In [155]:
np.random.random(size = 4)

array([0.08346624, 0.77581075, 0.72496493, 0.49703439])

      lub array 2-wymiarowy

In [156]:
np.random.random((2,3))                                                         # stworzy macierz dwuwymiarową w tym przypadku 2x3 z elementami losowymi

array([[0.2223691 , 0.17690076, 0.09854059],
       [0.33919855, 0.8555744 , 0.34282367]])

5) Losowa liczba calkowita

In [157]:
np.random.randint(10,20)                                                        # trzeba podac zakres

17

      lub zestaw

In [158]:
np.random.randint(1, 11, size=5)

array([7, 5, 7, 5, 9])

In [159]:
np.random.randint([2, 3, 10], 20)                           # wygeneruje macierz 1x3 gdzie lista w tym przypadku [2, 3, 10] to dolny granica przedziału, a 20 górna granica. 
                                                            # Jeśli chcemy wiekszą macierz to dodajemy liczby w zakresie

array([15, 17, 18])

In [160]:
np.random.randint([2, 3, 10, 15], 20)

array([ 6, 13, 16, 15])

In [161]:
np.random.randint(7, [20, 30, 10])                         # wygeneruje macierz 1x3 gdzie lista w tym przypadku [20, 30, 10] to górna granica przedziału, a 7 dolna granica. 
                                                           # Jeśli chcemy wiekszą macierz to dodajemy liczby w zakresie

array([17, 21,  8])

In [162]:
np.random.randint(1, 5, size=(2, 4))                                            # stworzy macierz 2x4, z losowymi elementami z przedzialu od 1 do 5

array([[4, 4, 2, 1],
       [1, 3, 1, 2]])

# ***STATYSTYKA***

1) Różnica max - min wartośći dla tablicy (lub kazdego wiersza/kolumny)

In [163]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [164]:
np.ptp(macierz2)                                                                # max = 9, min = 5, 9 - 5 = 4

4

In [165]:
np.ptp(macierz2, axis = 0)                                                      # różnica dla kazdej kolumny bo drugi argument to 0

array([1, 0, 1])

In [166]:
np.ptp(macierz2, axis = 1)                                                      # różnica dla kazdego wiersza bo drugi argument to 1

array([4, 4])

2) Mediana

In [167]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [168]:
np.median(macierz2)                                                             # mediana dla calej tablicy

8.0

In [169]:
np.median(macierz2, axis = 0)                                                   # mediana dla kazdej kolumny bo drugi argument to 0

array([8.5, 5. , 8.5])

In [170]:
np.median(macierz2, axis = 1)                                                   # mediana dla kazdego wiersza bo drugi argument to 1

array([8., 8.])

3) średnia

In [171]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [172]:
np.mean(macierz2)                                                               # średnia dla calej tablicy

7.333333333333333

In [173]:
np.mean(macierz2, axis = 0)                                                     # średnia dla kazdej kolumny bo drugi argument to 0

array([8.5, 5. , 8.5])

In [174]:
np.mean(macierz2, axis = 1)                                                     # średnia dla kazdego wiersza bo drugi argument to 1

array([7.33333333, 7.33333333])

4) Odchylenie standardowe

In [175]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [176]:
np.std(macierz2)

1.699673171197595

5) Wariancja

In [177]:
macierz2

array([[9, 5, 8],
       [8, 5, 9]])

In [178]:
np.var(macierz2)

2.888888888888889